/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface KeyEvent {
  key: string
  code: string
  eventType: string
  ctrl: boolean
  alt: boolean
  shift: boolean
  meta: boolean
  platformCode: number
  scanCode: number
  usbHid: number
}
export declare function start_grab(callback: (...args: any[]) => any): void
export declare function stop_grab(): void
